#!/bin/bash

usage(){
    echo -e "Usage:"
    echo -e "    create-tags [OPTIONS] [TARGET_DIR]" 
    echo
    echo -e "Options:"
    echo
    echo -e "  -h --help             \tdisplay this help message."
    echo -e "  -e --exclude DIRECTORY\texclude directories for ctags."
    echo -e "                        \tcan be used for multiple declarations."
    echo -e "  -f FILE               \tthe path of created tags."
    echo
    echo -e "Examples:"
    echo
    echo -e "  create-tags"
    echo -e "      create tags recursively in current directory and put it in current directory."
    echo -e "  create-tags ."
    echo -e "      create tags recursively in current directory and put it in current directory."
    echo -e "  create-tags . ./tags"
    echo -e "      create tags recursively in current directory, name it tags and put it in current directory."
    echo -e "  create-tags ~/source ~/tags"
    echo -e "      create tags recursively in ~/source, name it tags and put it in home directory."
    echo
    echo -e ""
    echo -e "  Version 1.0.0"
    echo -e "  Copyright (C)Leyuan Pan"
    echo -e "  leyuanpan@gmail.com"
    echo -e "  2016-10-11"
}

TARGET_DIR=
TAGS_PATH=
EXCLUDE=

while [[ $# -gt 0 ]]
do
    case "$1" in
        -h|--help)
            usage
            exit
            ;;
        -f)
            TAGS_PATH="$2"
            shift
            ;;
        -e|--exclude)
            EXCLUDE="${EXCLUDE} --exclude=$2"
            shift
            ;;
        *)
            TARGET_DIR="$1"
            ;;
    esac
    shift
done

if [[ "${TARGET_DIR}" -eq "" ]]
then
    TARGET_DIR=`pwd`
fi

if [[ "${TAGS_PATH}" -eq "" ]]
then
    TAGS_PATH="${TARGET_DIR}/tags"
fi

# create tags
echo "ctags -R --c++-kinds=+p --fields=+iaS --extra=+q ${EXCLUDE} -f ${TAGS_PATH} ${TARGET_DIR}"
ctags -R --c++-kinds=+p --fields=+iaS --extra=+q ${EXCLUDE} -f ${TAGS_PATH} ${TARGET_DIR}

